import { newsType } from './constants';

export const deliveries = [{
  id: 1,
  title: "移远通信",
  enTitle: "QUECTEL Co., Ltd",
  subTitle: "行业分类:科技与互联网",
  enSubTitle: "Industry Category: TMT",
  img: "291--upload-images-20190821-j62195898.jpg",
  images: [
    'j155561711.jpg',
    'j155561712.jpg',
    'j155561713.jpg',
    'j155561714.jpg',
    'j155561715.jpg',
    'j155561716.jpg'
  ],
  descript: '上海移远通信技术股份有限公司是全球领先的物联网技术的领导者，致力于为全球客户提供一流的无线通信解决方案。公司产品主要应用于无线支付、车载运输、无人驾驶、智能计量、智慧城市、智能安防、无线网关等领域，服务终端客户超过3,000家，分布于全球150多个国家和地区。2016-2018年度移远通信分别实现营业收入5.73亿元、16.6亿元和27亿元，年复合增长率超过67%。2018年公司物联网无线通信模块出货量全球第一，销售规模全球第二。2019年5月，公司通过证监会审核，首发成功过会。',
  enDescript: `QUECTEL Co., Ltd. is a professional developer of Internet of Things (IoT) technologies. QUECTEL provides wireless communication solutions for customers, which are mainly used in wireless payment, vehicle transportation, intelligent metering, intelligent city, intelligent security and wireless gateway. QUECTEL is located in Shanghai, serving more than 3,000 terminal clients, which are distributed in over 150 countries and regions. In 2016-2018, the income from the main business of QUECTEL maintained a rapid growth trend, with operating income of 573 million yuan, 1.66 billion yuan and 2.7 billion yuan respectively, with a compound annual growth rate of over 67%. In 2018, the company's IoT wireless communication module shipments ranked first in the world, and its sales volume ranked second in the world. On May 30, 2019, the company passed the examination of the CSRC.`,
}, {
  id: 2,
  title: "光通天下",
  enTitle: "GTTX Co., Ltd",
  subTitle: "行业分类:科技与互联网",
  enSubTitle: "Industry Category: TMT",
  img: "291--upload-images-20190821-j43410096.jpg",
  images: [
    'j155561772.jpg',
    'j155561773.jpg',
    'j155561774.jpg',
    'j155561775.jpg',
    'j155561776.jpg',
    'j155561777.jpg',
    'j155561771.jpg',
  ],
  descript: `光通天下网络科技股份有限公司是国内最早一批进入专业抗DDoS攻击服务领域的网络安全企业之一，公司具备全国7T级云清洗能力，亚太地区DDoS防护领域排名第一；公司单点防御T级水平，国内DDoS防护领域排名第一。<br/>
  光通天下与华为建立联合抗DDoS攻击实验室，公司现已形成以浙江、重庆、广东、陕西、河南、江苏为核心节点的国内骨干网络，与中国电信、中国联通、中国移动等基础电信运营商保持着良好合作关系。公司与国内知名互联网企业建立了业务合作关系，包括:腾讯云、华为云、星云融创（百度子公司）、幻电（哔哩哔哩）、网宿科技、金山云、盛大比格云等。公司于2019年5月向上交所科创板提交申报材料，顺利上市后将成为国内网络安全DDoS防护领域第一股。`,
  enDescript: `GTTX Co., Ltd. is one of the earliest domestic network security enterprises to enter the professional DDoS attack service field.. The company has 7T-level cloud cleaning capability in the country, ranking first in the DDoS protection field in the Asia-Pacific region; the company has a single-point defense T-level and ranks first in the domestic DDoS protection field.<br/>
  GTTX has cooperated with Huawei to provide anti-DDOS network security services to public cloud customers. The company has formed a domestic backbone network with Zhejiang, Chongqing, Guangdong, Shanxi, Henan and Jiangsu as the core nodes. GTTX has established business partnerships with well-known Internet companies in China, including: Tencent Cloud, Huawei Cloud, Baidu, Blibli, NetScience Technology, Jinshan Cloud, Shengda Biggeryun and so on. GTTX has submitted the application materials to the CSRC in May 2019. After GTTX successfully listing on the science and technology innovation board, it will become the first share in the domestic network security DDoS protection field.`,
}, {
  id: 3,
  title: "Video++",
  enTitle: "Video++",
  subTitle: "行业分类:人工智能",
  enSubTitle: "Industry Category: AI Program",
  img: "291--upload-images-20190819-j146717419.jpg",
  images: [
    'j155561741.jpg',
    'j155561742.jpg',
    'j155561743.jpg',
    'j155561744.jpg',
  ],
  descript: `上海极链网络科技有限公司（“Video++”）为人工智能+文化娱乐产业的科技独角兽企业。Video++深耕以文娱为基础的计算机视觉技术的自主研发，经过迭代升级，构筑了强大的技术壁垒。Video++人脸识别率高达99.9%，其他场景识别率均高于95.0%。公司的AI算力也进一步升级达到1,590万亿次/秒，远超同行业水平；公司AI团队在2018、2019连续两年Google地标识别挑战赛中获得冠军。Video++主营业务为视频AI广告、视频电商和互动娱乐，已与优酷、爱奇艺、芒果、抖音等国内65%视频流量平台合作。Video++AI营销平台服务逾百家品牌广告主，与数千家品牌商、视频应用、供应链建立合作。 `,
  enDescript: `Video++ is a technology unicorn enterprise for the artificial intelligence & cultural entertainment industry. Video++ deeply cultivates the independent research and development of computer vision technology based on entertainment, and it has been upgraded to build a strong technical barrier. Video++ face recognition rate is as high as 99.9%, and other scene recognition rates are higher than 95.0%. The company's AI computing power has also been further upgraded to 1,590 trillion times / second, far exceeding the industry level; the company. Video++ AI team won the championship in the Google Landmark Recognition Challenge for two consecutive years in 2018 and 2019. Video++ has collaborated with video websites or apps such as Youku, Iqiyi, Mango TV, Douying, Douyu TV, Panda TV which owns 65% video resource. V++AI marketing platform serves more than 100 brand advertisers.`,
}, {
  id: 4,
  title: "叠境数字",
  enTitle: "Dgene",
  subTitle: "行业分类:人工智能",
  enSubTitle: "Industry category:VR/AR",
  img: "291--upload-images-20190821-j131862127.jpg",
  images: [
    'j155561745.jpg',
    'j155561746.jpg',
    'j155561747.jpg',
    'j155561748.jpg',
    'j155561749.jpg',
    'j155561750.jpg',
    'j155561751.jpg',
    'j155561752.jpg',
  ],
  descript: `叠境数字科技（上海）有限公司（DGene）拥有全球领先的光场和人工智能技术，首创了独特的动态光场拍摄系统和云端处理服务，应用于虚拟现实、增强现实、三维重建、安防布控等领域，也是目前国内唯一一家能提供动态真人三维模型拍摄技术的公司。公司拥有16项发明专利，8项软件著作权。公司核心团队包括上海科技大学虞教授、麻省理工大学杨博士、微软研究院前首席研究员马博士、3D成像领域专家洪煦。`,
  enDescript: `DGene is the world's leading optical field technology company, with the top optical field technology and artificial intelligence technology, for VR, AR and flat display terminals to provide a super level of 3D content solutions and new ways of expression. DGene has 16 invention patents and 8 software copyrights. The company was co-founded by professor Yu from Shanghai  science and technology university, Dr. Yang, former principal researcher Dr. Ma from Microsoft research, and expert Hong Xu in the field of 3D display and imaging in May 2016 in Shanghai. `,
}, {
  id: 5,
  title: "苏州能讯",
  enTitle: "Dynax Semiconductor Inc.",
  subTitle: "行业分类:半导体",
  enSubTitle: "Industry Category: Semiconductor",
  img: "291--upload-images-20190821-j62195895.jpg",
  images: [
    'j155561781.jpg',
    'j155561782.jpg',
    'j155561783.jpg',
    'j155561784.jpg',
    'j155561785.jpg',
    'j155561786.jpg',
    'j155561787.jpg',
  ],
  descript: `苏州能讯高能半导体有限公司是目前中国唯一一家以IDM模式自主生产第三代半导体氮化镓芯片及射频功放管（应用于5G基站建设）的公司，产品性能名列全球前三。截至2018年底，公司在氮化镓射频器件领域共拥有279件专利申请，其中国际专利71件。专利布局完整，覆盖整条生产环节，拥有数量全球排名第三，仅次于美国科锐（Cree）与日本住友（Sumitomo）。能讯半导体作为国内第一家氮化镓芯片及功放管的民营供应商，目前客户包括中兴通讯、大唐移动等，未来公司规模将伴随5G建设发展迎来高速增长。`,
  enDescript: `Dynax Semiconductor Inc. currently is the only company in China that produces third-generation semiconductor GaN chips in IDM mode. Its main products are GaN RF power amplifier tubes，which are necessary for 5G base station construction. The products performance rank among the top three in the world. Until 2018, the company has had a total of 279 patent applications in the field of GaN RF devices, including 71 international patents. The patent layout is complete, covering the entire production process, and the number of patents ranked third in the world, after Cree and Sumitomo, in the end of 2018. Dynax is the first private supplier of GaN chips in China, and its current customers include ZTE, Datang Mobile, etc. In the future, the company's business will grow rapidly with the development of 5G.`,
}, {
  id: 6,
  title: "引航生物",
  enTitle: "Suzhou LeadBiotechnology Co., Ltd",
  subTitle: "行业分类:生物技术",
  enSubTitle: "Industry Category: Biotechnology",
  img: "291--upload-images-20190821-j62195899.jpg",
  images: [
    'j155561721.jpg',
    'j155561722.jpg',
    'j155561723.jpg',
    'j155561724.jpg',
    'j155561725.jpg',
    'j155561726.jpg',
  ],
  descript: `苏州引航生物科技有限公司创始人谢新开博士为资深科学家，加州大学洛杉矶分校化学和生物工程博士，加州伯克利大学博士后，美国绿色化学总统挑战奖的获得者。公司核心团队在合成生物学、代谢工程、酶工程和绿色化学及其产业化方面积累了丰富的研发和产业化经验，目前共申请25项发明专利（含5项PCT专利，已取得3项专利授权），开发了40余种酶制剂产品，建立了千余种酶种资源库和自动化高通量筛选工作站。乔贝资本在首轮投资3500万元后，于2019年6月追加投资3000万元。`,
  enDescript: `Dr. Xinkai Xie, the founder of Suzhou LeadBiotechnology Co., Ltd, got Ph.D. in chemical and biological engineering department at UCLA and as a post-doctor at University of California, Berkeley. Dr. Xie received US Green Chemistry Presidential Challenge Award at UCLA. The core term members have rich experience in R&D and industrialization in biotechnology by applying synthetic biology, metabolic engineering, enzyme engineering and chemistry. Leadbiotechnology has applied for 25 discovery patents, including 5 PCT and 3 patents authorization are obtained. Up to now, more than 40 enzymes and 1000 total enzyme libraries have been developed. Meanwhile, automated high-throughput screening platform has been set up for future R&D.  Chobe capital has invested 35 million and will invest additional 30 million in June 2019.`,
}, {
  id: 7,
  title: "丰科生物",
  enTitle: "Finc Biotechnology Co., Ltd",
  subTitle: "行业分类:生物技术",
  enSubTitle: "Industry Category: Biotechnology",
  img: "291--upload-images-20190821-j54869834.jpg",
  images: [
    'j155561761.jpg',
    'j155561762.jpg',
    'j155561763.jpg',
    'j155561764.jpg',
    'j155561765.jpg',
    'j155561766.jpg',
    'j155561767.jpg',
  ],
  descript: `上海丰科生物科技股份有限公司，专业从事食用菌的研发、生产、加工和销售，公司股东包括行业权威机构“上海市农业科学院”，并获得“全国食用菌行业最具影响力企业”、“高新技术企业”、“上海市知识产权示范企业”等荣誉称号。公司具有10多年蟹味菇、白玉菇栽培技术经验，目前产能已达国内第一，且市场占有率长年居全国首位。公司生产的蟹味菇、白玉菇营养丰富，无人工添加剂，并荣膺绿色食品A级产品、中国名牌农产品、上海市专利新产品等称号。公司拥有4项高新技术成果转化项目、22项发明专利。`,
  enDescript: `Shanghai Finc Biotechnology Co.,Ltd. specializes in mushroom R&D, production, processing and sales. Shanghai academy of agriculture sciences, the industrial authority, is one of the company's shareholders. What’s more, it’s awarded the titles of the most influential enterprise in the domestic mushroom industry, the high-tech enterprise, Shanghai intellectual property rights demonstration enterprise and so on. The company has more than 10 years of experience in cultivation technology of crab flavor mushroom and white jade mushroom. At present, its production capacity has reached the first place in China, and its market share has ranked the first all year round. The crab flavor mushroom and white jade mushroom produced by the company are rich in nutrition without artificial additives, both of which are also awarded the green food grade A products, Chinese famous agriculture products, Shanghai patent new product and so on. The company has 4 high-tech achievement transformation projects and 22 invention patents.`,
}, {
  id: 8,
  title: "依依股份",
  enTitle: "Yiyi Hygiene Products Co., Ltd",
  subTitle: "行业分类:消费升级",
  enSubTitle: "Industry Category: Consumption Upgrading Industry",
  img: "291--upload-images-20190821-j62195897.jpg",
  images: [
    'j155561701.jpg',
    'j155561702.jpg',
    'j155561703.jpg',
    'j155561704.jpg',
    'j155561705.jpg',
    'j155561706.jpg',
    'j155561707.jpg',
  ],
  descript: `天津依依卫生用品股份有限公司是目前亚洲最大的宠物垫生产厂商，公司在宠物用品、护理领域深耕20余年，拥有丰富的研发、生产以及销售经验。公司的主营产品以宠物用品为主、成人护理用品为辅。公司生产规模亚洲排名第一，作为与品牌制造商、贸易商、零售商直接对接的宠物用品生产厂商，公司的主要产品通过沃尔玛、亚马逊、日本伊藤、日本山善、PETSMART INC、伊藤百货等大型零售商销往包括美、日、欧、东南亚等四十多个国家地区。`,
  enDescript: `Tianjin Yiyi Hygiene Products Co., Ltd. is currently the largest pet pad manufacturer in Asia. The company has been deeply involved in pet supplies and nursing for more than 20 years and has extensive experience in R&D, production and sales. The company's main products are mainly pet products and supplemented by adult care products. The company's production scale ranks first in Asia. As a pet product manufacturer directly connected with brand manufacturers, traders and retailers, the company's main products are through large-scale retail such as Wal-Mart, Amazon, Japan Ito, Yamazaki, PETSMART INC, and Ito. The business is sold to more than 40 countries and regions including the United States, Japan, Europe and Southeast Asia.`,
}, {
  id: 9,
  title: "微能科技",
  enTitle: "Wcansoft Co., Ltd",
  subTitle: "行业分类:消费升级",
  enSubTitle: "Industry Category: Consumption Upgrading Industry",
  img: "291--upload-images-20190821-j62195896.jpg",
  images: [
    'j155561791.jpg',
    'j155561792.jpg',
  ],
  descript: `浙江微能科技有限公司是目前国内最大的积分服务运营商之一，主要业务版块包括泛积分O2O运营、聚合支付、精准营销以及企业福利积分计划。微能科技上游客户包括三大移动运营商、多家全国性银行及众多地方性银行、上市公司、保险公司、航空公司等。下游拥有肯德基（全国独家）、星巴克、Costa咖啡等众多国际、国内一线品牌商户资源，商户资源超过万家。同时，公司被指定为全体党员学习APP“学习强国”唯一积分运营商。公司深耕积分消费领域，并将持续开拓包括企业采购、互联网平台、支付出行及福利平台业务，未来希望打造全产业全渠道通兑积分平台，从而将积分价值最大化。`,
  enDescript: `Zhejiang Wcansoft Co., Ltd is one of the largest reward program providers in China. The business of Wcan includes reward program O2O operating, aggregate payment, precision marketing and benefits program for company. The company’s clients include three major mobile operators, more than 10 national and many local banks ,public companies, insurance companies and airplane companies. Their suppliers are well-known companies including KFC（National exclusive）, Starbucks， Costa coffee and many other worldwide and national famous brands. Wcansoft has cooperated with more than 10 thousands stores. Also, Wcansoft was appointed as the only reward program operator of LEARNING POWER APP for the Communist Party of China’s all members. Wcansoft focus on reward program and is exploring including large enterprises’ purchase and welfare platform, internet platform, public transportation. Their vision is to create the reward program linked to all industries to maximize the value.`,
}];

export const newsData = [{
  id: 1,
  type: newsType.hyxw,
  title: "诺奖得主朱棣文：生命如此短暂，要对你所爱倾注深情",
  enTitle: "No english",
  date: 1592316480148,
  count: 86,
  img:"206--upload-images-20190819-j341819272.jpg",
  author: "张三",
  content: `<p>创业公司的早期，创始人所做的重要决定就是招什么样的初始成员，包括前端工程师、后端工程师、产品经理、销售和设计师等。如果你给这些职位招到了对的人，你的公司、你的未来员工和你的投资人都会感激你。但如果你招错了人，可能就会遇到如噩梦般的事情。<br> &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;<br>创业公司的早期，创始人所做的重要决定就是招什么样的初始成员，包括前端工程师、后端工程师、产品经理、销售和设计师等。如果你给这些职位招到了对的人，你的公司、你的未来员工和你的投资人都会感激你。但如果你招错了人，可能就会遇到如噩梦般的事情。创业公司的早期，创始人所做的重要决定就是招什么样的初始成员，包括前端工程师、后端工程师、产品经理、销售和设计师等。如果你给这些职位招到了对的人，你的公司、你的未来员工和你的投资人都会感激你。但如果你招错了人可能就会遇到如噩梦般的事情。</p><div class="divImg"><img src="images/news/j35.jpg"  title="" alt=""></div><p>创业公司的早期，创始人所做的重要决定就是招什么样的初始成员，包括前端工程师、后端工程师、产品经理、销售和设计师等。如果你给这些职位招到了对的人，你的公司、你的未来员工和你的投资人都会感激你。但如果你招错了人，可能就会遇到如噩梦般的事情。<br> &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;<br>创业公司的早期，创始人所做的重要决定就是招什么样的初始成员，包括前端工程师、后端工程师、产品经理、销售和设计师等。如果你给这些职位招到了对的人，你的公司、你的未来员工和你的投资人都会感激你。但如果你招错了人，可能就会遇到如噩梦般的事情。创业公司的早期，创始人所做的重要决定就是招什么样的初始成员，包括前端工程师、后端工程师、产品经理、销售和设计师等。如果你给这些职位招到了对的人，你的公司、你的未来员工和你的投资人都会感激你。但如果你招错了人可能就会遇到如噩梦般的事情。
  &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;</p> `,
  enContent: "No english",
}, {
  id: 2,
  type: newsType.IPO,
  title: "IPO新闻",
  enTitle: "No english",
  date: 1592316480148,
  count: 86,
  img:"206--upload-images-20190819-j341819272.jpg",
  author: "张三",
  content: `<p>创业公司的早期，创始人所做的重要决定就是招什么样的初始成员，包括前端工程师、后端工程师、产品经理、销售和设计师等。如果你给这些职位招到了对的人，你的公司、你的未来员工和你的投资人都会感激你。但如果你招错了人，可能就会遇到如噩梦般的事情。<br> &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;<br>创业公司的早期，创始人所做的重要决定就是招什么样的初始成员，包括前端工程师、后端工程师、产品经理、销售和设计师等。如果你给这些职位招到了对的人，你的公司、你的未来员工和你的投资人都会感激你。但如果你招错了人，可能就会遇到如噩梦般的事情。创业公司的早期，创始人所做的重要决定就是招什么样的初始成员，包括前端工程师、后端工程师、产品经理、销售和设计师等。如果你给这些职位招到了对的人，你的公司、你的未来员工和你的投资人都会感激你。但如果你招错了人可能就会遇到如噩梦般的事情。</p><div class="divImg"><img src="images/news/j35.jpg"  title="" alt=""></div><p>创业公司的早期，创始人所做的重要决定就是招什么样的初始成员，包括前端工程师、后端工程师、产品经理、销售和设计师等。如果你给这些职位招到了对的人，你的公司、你的未来员工和你的投资人都会感激你。但如果你招错了人，可能就会遇到如噩梦般的事情。<br> &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;<br>创业公司的早期，创始人所做的重要决定就是招什么样的初始成员，包括前端工程师、后端工程师、产品经理、销售和设计师等。如果你给这些职位招到了对的人，你的公司、你的未来员工和你的投资人都会感激你。但如果你招错了人，可能就会遇到如噩梦般的事情。创业公司的早期，创始人所做的重要决定就是招什么样的初始成员，包括前端工程师、后端工程师、产品经理、销售和设计师等。如果你给这些职位招到了对的人，你的公司、你的未来员工和你的投资人都会感激你。但如果你招错了人可能就会遇到如噩梦般的事情。
  &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;</p> `,
  enContent: "No english",
}, {
  id: 3,
  type: newsType.IPO,
  title: "IPO新闻1111",
  enTitle: "No english111",
  date: 1592316480148,
  count: 86,
  img:"206--upload-images-20190819-j341819272.jpg",
  author: "张三",
  content: `<p>创业公司的早期，创始人所做的重要决定就是招什么样的初始成员，包括前端工程师、后端工程师、产品经理、销售和设计师等。如果你给这些职位招到了对的人，你的公司、你的未来员工和你的投资人都会感激你。但如果你招错了人，可能就会遇到如噩梦般的事情。<br> &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;<br>创业公司的早期，创始人所做的重要决定就是招什么样的初始成员，包括前端工程师、后端工程师、产品经理、销售和设计师等。如果你给这些职位招到了对的人，你的公司、你的未来员工和你的投资人都会感激你。但如果你招错了人，可能就会遇到如噩梦般的事情。创业公司的早期，创始人所做的重要决定就是招什么样的初始成员，包括前端工程师、后端工程师、产品经理、销售和设计师等。如果你给这些职位招到了对的人，你的公司、你的未来员工和你的投资人都会感激你。但如果你招错了人可能就会遇到如噩梦般的事情。</p><div class="divImg"><img src="images/news/j35.jpg"  title="" alt=""></div><p>创业公司的早期，创始人所做的重要决定就是招什么样的初始成员，包括前端工程师、后端工程师、产品经理、销售和设计师等。如果你给这些职位招到了对的人，你的公司、你的未来员工和你的投资人都会感激你。但如果你招错了人，可能就会遇到如噩梦般的事情。<br> &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;<br>创业公司的早期，创始人所做的重要决定就是招什么样的初始成员，包括前端工程师、后端工程师、产品经理、销售和设计师等。如果你给这些职位招到了对的人，你的公司、你的未来员工和你的投资人都会感激你。但如果你招错了人，可能就会遇到如噩梦般的事情。创业公司的早期，创始人所做的重要决定就是招什么样的初始成员，包括前端工程师、后端工程师、产品经理、销售和设计师等。如果你给这些职位招到了对的人，你的公司、你的未来员工和你的投资人都会感激你。但如果你招错了人可能就会遇到如噩梦般的事情。
  &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;</p> `,
  enContent: "No english",
},];