import Cookies from 'js-cookie';
import { intlType } from './constants';
export const en = {
  home: "HOME",
  about: "ABOUT US",
  about1: "Introduction",
  about2: "Founder",
  about3: "Core Team",
  about4: "Enterprise Characteristics",
  about5: "Capital concept",
  delivery: "Invested Enterprises",
  delivery_name: "Entry Name",
  news: "NEWS",
  news1: "Industry News",
  news2: "IPO",
  news3: "news on current events",
  news4: "Jobe Dynamics",
  news5: "Publicity Document",
  company_culture: "CORPORATE CULTURE",
  QB_welfare: "PUBLIC WELFARE",
  join_us: "JOIN US",
  join1: "Contact us",
  join2: "Recruit",
  index_desc:`Chobe Capital was established in September 2016 and headquartered in Shanghai. Chobe Capital is specialized in professional equity investment, mainly focusing on the Pre-IPO and Venture Capital projects. 
  Chobe Capital has had rich experience in TMT, Biotechnology, Consumption Upgrading and Environmental Protection Industries.`,
  index_more:"DETAILS",
  footer_01:"Welcome to cooperate with us, please contact us",
  footer_02:"欢迎您和我们开展合作 请联系我们",
  about_name01:"Lin Hua",
  about_name02:"Rui Zhou",
  about_name03:"Yangjia Ren",
  about_desc01:"Executive Director, Bachelor of Economics of Shanghai Jiao Tong University. She served as Executive General Manager of GUOSEN Securities, with many years of industry research experience and more than 10 years’ experience in corporate customer service, focusing on Venture Capital, Equity Investment, Refinancing and M&A. Currently, she focuses on VC and PE projects in the fields of Biotech and TMT. ",
  about_desc02:"Senior Investment Manager，Master of Biological System Engineering Department from Virginia Tech. Mr. Zhou worked in Investment Bank Department in Sealand Securities. He participated in due diligence for several companies and has great experience in equity and bond projects. Because of his education career, Mr. Zhou has great view in Biological industry. Now the fields which Mr. Zhou focus on are related to biotechnology and internet.",
  about_desc03:"Investment Manager，Master of Economics from University of Leeds. She joined due diligence for several companies and has outstanding capability of communication and collaborate with teammates.",
  about_ms01:"Help excellent entrepreneur to achieve their goals",
  about_ms02:"Create value for investors and customers",
  about_ms03:"Integrity, professionalism, fairness and transparency",
  about_ss01:"Create Value",
  about_ss02:"Strategic Resources",
  about_ss03:"Standard Operation",
  about_ll01:"Providing comprehensive customer service after investment, insisting on forging an investment banking style service. Chobe Capital persist in creating value for customers.",
  about_ll02:"Chobe Capital has strong business resource, according to the characteristics of the customer industry, business status, docking customers for downstream customers resources to enhance company's business scale and improve the customer structure.",
  about_ll03:"In accordance with IPO standards, Chobe Capital helps enterprises form standardize operation and enhance the management level of enterprises to meet IPO standards.",
  delivery1:"Project name",
  delivery2:"TMT",
  delivery3:"Biomedicine",
  delivery4:"Consumption upgrade",
  culture1:"On the way",
  culture2:"Other",
  welfare:`Some people say that "the significance of doing public welfare lies in finding the intrinsic value of life" , while referring to public welfare always reminds people of children in poor areas, and children are the hope of future social development, however, children in mountainous areas have limited educational resources because of their living environment. Chobe capital has always had a vision of being able to take on this social responsibility and grow up with children who struggle but still study hard, believing that in the future they will be better able to give back to society and achieve self-worth. The company is currently setting up a charitable trust, looking for influential children's public welfare projects, follow-up we will continue to report, please look forward to.`,
  join_cc01:"Position",
  join_cc02:"Number",
  join_cc03:"Education",
  join_cc04:"Place",
  join_cc05:"Working hours",
  post:"Job description",
  requirements:"Job requirements",
  application:"Apply position",
  preview:"< Previous",
  next:"Next >",
  address:"Address:",
  tel:"Tel:",
  email:"E-mail:",
  addressStr:" No. 868 Sakura Road, Pudong New District, Shanghai Construction Datang International Plaza, Flat A, Room 2001"
}
export const cn = {
  home: "首页",
  about: "关于我们",
  about1: "公司简介",
  about2: "创始人",
  about3: "核心团队",
  about4: "企业特色",
  about5: "投资理念",
  delivery: "被投企业",
  delivery_name: "企业名称",
  news: "新闻动态",
  news1: "行业新闻",
  news2: "IPO",
  news3: "时事新闻",
  news4: "乔贝动态",
  news5: "被投企业公众号文章",
  company_culture: "企业文化",
  QB_welfare: "乔贝公益",
  join_us: "加入我们",
  join1: "招聘信息",
  join2: "联系我们",
  index_desc:`乔贝资本创立于2016年9月，总部位于上海，于 2017 年 1 月在中国证券投资基金业协会登记为私募基金管理人（登记编码：P1061185），是一家专注于股权投资的专业化基金管理公司。自成立以来，乔贝资本锐意进取、秉承专业，在专注投资领域完成布局，树立了专业化的投资风格。
  <br> <br>
  乔贝资本对所有潜在投资机会都持开放态度，并专注于已经拥有投资经验的领域...`,
  index_more:"了解详情",
  footer_01:"欢迎您和我们开展合作 请联系我们",
  footer_02:"WELCOME TO COOPERATE WITH US, PLEASE CONTACT US",
  about_name01:"化 琳",
  about_name02:"周 睿",
  about_name03:"姜思丞",
  about_desc01:"执行董事，上海交通大学经济学学士，曾任国信证券上市公司部执行总经理，十余年企业客户服务经验，业务领域涵盖风险投资、股权投资、上市公司融资、并购重组等，具有丰富的投资管理经验。目前专注于生物技术、科技与互联网领域的早期、成长期项目。",
  about_desc02:"风控总监，弗吉尼亚理工大学生物系统工程硕士，曾就职国海证券股份有限公司投资银行部，参与过多家公司尽职调查及股份改制工作，具备较为丰富的股权及债权类项目经验，尤其针对生物行业具有较深理解。目前专注于生物技术与互联网领域相关项目。",
  about_desc03:"投资经理，美国福特汉姆大学金融学硕士，中央财经大学经济学学士曾供职于券商研究所，参与过能讯、叠境科技等多家公司的尽职调查，具备良好的研究能力和团队协作能力。",
  about_ms01:"根据企业不同发展阶段，协助企业逐步建立起规范严谨的财务及内控制度，建立健全完善的法人治理结构及三会制度等，确保企业规范运作，为企业未来进入资本市场打好基础。",
  about_ms02:"结合企业所处行业，根据企业发展阶段，及时对接相关行业上下游资源（尤以上市公司资源为主），改善企业的客户结构；",
  about_ms03:"乔贝资本承担并协助已投标的后续所有轮次的融资工作，减轻企业负担及减少因企业对资本市场的不理解造成的融资失败、估值不公允等风险；乔贝资本团队在企业发展成熟阶段，在投行、会所、律所进场前即协助企业提前启动 IPO 前的规范工作；乔贝资本团队在企业 IPO 过程中，负责帮助企业协调其与中介机构的关系。",
  about_ss01:"创造价值",
  about_ss02:"战略资源",
  about_ss03:"规范运作",
  about_ll01:"为客户提供全方面的投后服务，竖持做一家精品投行风格基金管理公同。坚持在战略资源、规范运作及资本市场领域全面深入协助企业，为客户创造价值。",
  about_ll02:"乔贝资本凭借强大的投行团队，根据客户行业特性、经营现状，为客户对接上下游客户资源，提升公司业务规模，改善企业的客户结构。",
  about_ll03:"按照IPO标准，协助企业规范操，提升企业的管理水平减少客户上市障碍。",
  delivery1:"项目名称",
  delivery2:"TMT",
  delivery3:"生物医药",
  delivery4:"消费升级",
  culture1:"在路上",
  culture2:"其他",
  welfare:"有人说：“做公益的意义在于寻找生命的内在价值”，而提到公益总是让人不自觉地想到贫困地区的儿童，儿童是未来社会发展的希望，山区儿童却因为生活环境导致教育资源有限。乔贝资本一直怀有一份愿景，渴望能够担起这份社会责任，陪伴那些生活艰苦却依然努力学习的儿童一起成长，相信未来他们会更好地回馈社会，实现自我价值。公司目前正在设立慈善信托、寻找具有影响力的儿童公益项目，后续我司会陆续报道，敬请期待。",
  join_cc01:"职位名称",
  join_cc02:"职位数量",
  join_cc03:"学历",
  join_cc04:"工作地点",
  join_cc05:"发布时间",
  post:"岗位描述",
  requirements:"任职要求",
  application:"申请职位",
  preview:"< 前一张",
  next:"下一张 >",
  address:"地址:",
  tel:"电话:",
  email:"电子邮件:",
  addressStr:"上海市浦东新区樱花路868号建工大厦国际广场2001室"
}

export const switchIntl = () => {
  const $intlList = $("[data-intl]");
  const type = Cookies.get('page_intl');
  const intlObj = Number(type) === intlType.en ? en : cn;
  if (Number(type) === intlType.en) {
    $('#topMenu').removeClass('cn').addClass('en');
  } else {
    $('#topMenu').removeClass('en').addClass('cn');
  }
  $.each($intlList, function (index, item) {
    const value = $(item).data("intl")
    if (intlObj[value]) {
      $(item).html(intlObj[value]);
    }
  })
}